config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :pimped_cars, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
  end
  resources :promos, only: [:show]
  resources :bookings, only: [:index, :show, :edit, :update]
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pimped_car
  belongs_to :user
  validates :starts_at, presence: true, allow_blank: false
  validates :ends_at, presence: true, allow_blank: false
  validates :status, inclusion: { in: ["pending", "accepted", "declined"]}
end

app/models/pimped_car.rb
class PimpedCar < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, allow_blank: false
  validates :price_per_day, presence: true, numericality: { only_integer: true }
  validates :address, presence: true, allow_blank: false
  has_many :bookings
  has_one :promo
  has_attachment :photo
  validates :photo, presence: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/promo.rb
class Promo < ApplicationRecord
  belongs_to :pimped_car
  validates :discount, presence: true
  validates :limit_offer_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]
  has_many :pimped_cars, dependent: :nullify
  has_many :bookings

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  after_filter :store_action

  def store_action
    return unless request.get?
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      store_location_for(:user, request.fullpath)
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_bookings, only: [:show, :total, :edit, :update]

  def index
    # Get all the booking regarding the current user
    @bookings = current_user.bookings
    # Get all the cars related to a user
    @cars = PimpedCar.where("user_id = #{current_user.id}")
  end

  def show
    @owner = owner(@booking)
    @renter = renter(@booking)
    @total = total(@booking)
  end

  # def edit
  #   @status_available = ["declined", "accepted"]
  # end

  def update

    @booking.update(booking_params)
    if @booking.save
     redirect_to bookings_path
    else
      render :index
    end
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.starts_at = Date.strptime(booking_params[:starts_at], ("%m/%d/%Y"))
    @booking.ends_at = Date.strptime(booking_params[:ends_at], ("%m/%d/%Y"))
    @pimpedcar = PimpedCar.find(params[:pimped_car_id])
    @booking.pimped_car = @pimpedcar
    @booking.user = current_user
    @booking.status = "pending"
    if @booking.save
      #TODO : redirect to the booking show (with pending status)
      redirect_to booking_path(@booking)
    else
      render 'pimped_cars/show'
    end
  end

  private

  def set_bookings
    @booking = Booking.find(params[:id])
  end

  def owner(booking)
    pimped_car = PimpedCar.find(booking.pimped_car_id)
    owner_id = pimped_car.user_id
    @owner = User.find(owner_id)
    @owner
  end

  def renter(booking)
    renter = User.find(booking.user_id)
    renter_id = renter
    @renter = User.find(renter_id)
    @renter
  end

  def car(booking)
    @car = PimpedCar.find(booking.pimped_car_id)
    @car
  end

  def total(booking)
    start_date = booking.starts_at
    end_date = booking.ends_at
    pimped_car = PimpedCar.find(booking.pimped_car_id)
    price_per_day = pimped_car.price_per_day
    @total = (price_per_day * (end_date - start_date)) / 86400
  end

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at, :status, :user_id, :pimped_car_id)
  end

  helper_method :total, :owner, :renter, :car
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @disable_nav = true
  end
end

app/controllers/pimped_cars_controller.rb
require 'date'
class PimpedCarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_pimped_cars, only: [:show]

  def index
    unless params[:address].nil?
      @pimped_cars = PimpedCar.near(params[:address], params[:distance])
    else
      @pimped_cars = PimpedCar.where.not(latitude: nil, longitude: nil)
    end
    # if address is inside params (query string) >> @pimped_cars = PimpedCar.near
    # sinon comme d'hab
    @hash = Gmaps4rails.build_markers(@pimped_cars) do |pimped_car, marker|
      marker.lat pimped_car.latitude
      marker.lng pimped_car.longitude
      marker.infowindow render_to_string(partial: "/pimped_cars/map_box", locals: { pimped_car: pimped_car })
    end
  end

  def show
    @booking = Booking.new
    unless @pimped_car.promo.blank?
      @discount = (@pimped_car.promo.discount*100).to_i
      now = DateTime.now
      limit_time = @pimped_car.promo.limit_offer_date
       @difference = (limit_time - now).to_i
    end
  end

  def new
    @pimped_car = PimpedCar.new
  end

  def create
    @pimped_car = PimpedCar.new(set_params)
    @pimped_car.user_id = current_user.id
    if @pimped_car.save
      redirect_to pimped_cars_path(@pimped_car)
    else
      render :new
    end
  end

  private

  def set_params
    params.require(:pimped_car).permit(:name, :price_per_day, :description, :address, :photo)
  end

  def set_pimped_cars
    @pimped_car = PimpedCar.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_owner_bookings.html.erb
<div class="message-title">
  <div class="message-meta title">
    <p>User</p>
  </div>
  <div class="message-name title desktop">
    <p><strong>From</strong></p>
  </div>
  <div class="message-name title desktop">
    <p><strong>To</strong></p>
  </div>
  <div class="message-name title mobile">
    <p><strong>Date</strong></p>
  </div>
  <div class="message-name title user-details">
    <p><strong>Renter</strong></p>
  </div>
  <div class="message-body title">
    <div>
      <p><strong>Rented car</strong></p>
    </div>
  </div>

  <div class="message-status title">
    <p><strong>Statut</strong></p>
    <p><strong>Total</strong></p>
  </div>
</div>
<!-- Store each bookings relative to a car -->
<% bookings = @car.bookings %>
<!-- Iterate on bookings to display each booking for a car -->
<% bookings.each do |booking| %>
  <div class="message">
    <%= cl_image_tag renter(booking).facebook_picture_url, class: "avatar-large", width: 50, height: 50, gravity: "face", crop: :fill %>
    <div class="message-name desktop">
      <p><%= booking.starts_at.strftime("%m/%d/%Y") %></p>
    </div>
    <div class="message-name desktop">
      <p><%= booking.ends_at.strftime("%m/%d/%Y") %></p>
    </div>
    <div class="message-name mobile">
      <p><%= booking.starts_at.strftime("%m/%d") %></p>
      <p><%= booking.ends_at.strftime("%m/%d") %></p>
    </div>
    <div class="message-name user-details">
       <p class="text-center"><%= renter(booking).first_name %></p>

    </div>
    <div class="message-body">
        <div class="message-details">
          <p><%= link_to @car.name, pimped_car_path(booking.pimped_car_id) %></p>
      </div>
    </div>

      <div class="message-status text-left">
        <% if booking.status == "pending" %>
        <div class="boutons">
          <%= link_to "Accept", booking_path(booking, booking: {status: "accepted"}), class: "btn btn-success bouton", method: :patch %>
          <%= link_to "Decline", booking_path(booking, booking: {status: "declined"}), class: "btn btn-danger bouton", method: :patch %>
          </div>
        <% else %>
          <% if booking.status == "pending" %>
            <p class="pending"><%= booking.status %></p>
          <% elsif booking.status == "accepted" %>
            <p class="accepted"><%= booking.status %></p>
          <% elsif booking.status == "declined" %>
            <p class="declined"><%= booking.status %></p>
          <% end %>
        <% end %>
        <p class="price">$ <%= total(booking) %></p>
      </div>
  </div>
<% end %>

app/views/bookings/_user_bookings.html.erb
<div class="message-title">
  <div class="message-meta title">
    <p>Car</p>
  </div>
  <div class="message-name title desktop">
    <p><strong>From</strong></p>
  </div>
  <div class="message-name title desktop">
    <p><strong>To</strong></p>
  </div>
   <div class="message-name title mobile">
    <p><strong>Date</strong></p>
  </div>
  <div class="message-name title user-details">
    <p><strong>Owner</strong></p>
  </div>
  <div class="message-body title">
    <div>
      <p><strong>Rented car</strong></p>
    </div>
  </div>

  <div class="message-status title">
    <p><strong>Statut</strong></p>
    <p class="price"><strong>Total</strong></p>
  </div>
</div>

    <!-- Iterate on bookings to display each booking for a car -->
<% @bookings.each do |booking| %>
  <div class="message">
    <%= link_to pimped_car_path(booking.pimped_car_id) do %>
      <%= cl_image_tag car(booking).photo.path, class: "avatar-square", width: 50, height: 50, gravity: "face", crop: :fill %>
    <% end %>
    <div class="message-name desktop">
      <p><%= booking.starts_at.strftime("%m/%d/%Y") %></p>
    </div>
    <div class="message-name desktop">
      <p><%= booking.ends_at.strftime("%m/%d/%Y") %></p>
    </div>
    <div class="message-name mobile">
      <p><%= booking.starts_at.strftime("%m/%d") %></p>
      <p><%= booking.ends_at.strftime("%m/%d") %></p>
    </div>
     <div class="message-name user-details">
        <p><%= owner(booking).first_name %></p>
    </div>
    <div class="message-body">
        <div class="message-details">
          <p><%= link_to car(booking).name, pimped_car_path(booking.pimped_car_id) %></p>
      </div>
    </div>

      <div class="message-status text-left">
        <% if booking.status == "pending" %>
            <p class="pending"><%= booking.status %></p>
          <% elsif booking.status == "accepted" %>
            <p class="accepted"><%= booking.status %></p>
          <% elsif booking.status == "declined" %>
            <p class="declined"><%= booking.status %></p>
          <% end %>
        <p class="price">$ <%= total(booking) %></p>
      </div>
  </div>
<% end %>

app/views/bookings/index.html.erb
<% content_for(:title_tag) do %>
  My Bookings
<% end %>
<div class="container">
  <div class="row">
    <!-- Method call (defined has helper) to display or not the user bookings  -->

     <% if @bookings.empty? %>
     <% else %>
      <div class="col-xs-12 text-center">
        <h3 class="text-center car-list">My next rides</h3>
        <%= render partial: "user_bookings", object: @cars  %>
      </div>
      <% end %>
  </div>
  <div class="row owner-cars">
    <!-- Method call (defined has helper) to display or not owner bookings  -->
    <!-- Iteration on @cars to access each car and check if this car has been booked -->
    <% if @cars.any? { |car| car.bookings.empty? } %>
      <h3 class="text-center">Bookings for my Pimped Cars</h3>
    <% end %>
    <% @cars.each_with_index do |car, index| %>
      <% @car = car %>
      <% if car.bookings.empty? %>

        <div class="text-center car-list">
          <div class="car-list-div">
            <%= link_to pimped_car_path(car) do %>
              <h4 class="text-center car-list"><%= cl_image_tag car.photo.path, width: 50, height: 50, gravity: "face", crop: :fill, class: "avatar-rectangle" %> <%= car.name %></h4>
             <% end %>
           </div>
          <p>No reservations available yet for this car</p>
        </div>
      <% else %>
      <div class="car-list-div">
        <%= link_to pimped_car_path(car) do %>
          <h4 class="text-center car-list"><%= cl_image_tag car.photo.path, width: 50, height: 50, gravity: "face", crop: :fill, class: "avatar-rectangle" %> <%= car.name %></h4>
        <% end %>
      </div>
          <%= render partial: "owner_bookings", object: @car %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-sm-10 col-sm-offset-1 text-center">
      <h1>Nearly booked Rider!</h1>
      <p> Waiting for <span class="owner"><%= @owner.first_name %></span> to accept your request to ride an AWESOME Pimped car ! </p>
   </div>
  </div>

  <div class="row text-center">
    <div class="panel">
        <div class="col-sm-5">
          <div class="car_pic">
            <% if @booking.pimped_car.photo? %>
              <%= link_to pimped_car_path(@booking.pimped_car_id) do %>
                <%= cl_image_tag @booking.pimped_car.photo.path, width: 400, height: 200, crop: :fill %>
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="col-sm-7">
          <div class="booking-info">
            <div class ="status-box">
              <h4>Status: <span class="status"> <%= @booking.status %></span> </h4>
            </div>
            <div class=" booking-date-infos">
                <p> <%= @booking.starts_at.strftime("%A %d %B %Y") %></p>

                <p> <%= @booking.ends_at.strftime("%A %d %B %Y") %></p>
            </div>
            <div class="booking-total">
             <!--  <p>Number of days = <%= (@booking.ends_at - @booking.starts_at).to_i/86400 %> days</p> -->
              <p>Total = $<%= @total %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="backlink text-center">
        <%= link_to "Back to all your bookings", bookings_path, class: "btn btn-primary" %>
        <%= link_to "Back to catalog", pimped_cars_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="pattern">
  <video id="video" autoplay loop id="video-background" muted width="100%">
    <source src="http://res.cloudinary.com/dw5ekt0rf/video/upload/v1502966890/I%CC%87KAS_TEASER_TANITIM_yfy1yw.mp4" type="video/mp4">
  </video>

<%= link_to "Rent a PIMPED Car", pimped_cars_path, class: "btn-cta-home" %>
</div>

<div class="background-home">
  <div class="home_first_banner">
    <menu class="Menu">
      <% if user_signed_in? %>
      <li class="Menu-item" id="btn-1"> <%= link_to "Profile", bookings_path %></li>
      <% end %>
      <li class="Menu-item" id="btn-2"><%= link_to "Log in", new_user_session_path %></li>
      <li class="Menu-item" id="btn-3"><%= link_to "Add", new_pimped_car_path %></li>
      <li class="Menu-item" id="btn-4"><%= link_to "Cars", pimped_cars_path %></li>
    </menu>
  </div>

  <div class="card-group container">
    <div class="row row-home">
     <h2>"If the ride is more fly, then you must buy" - Snoopy</h2>
      <div class="col-xs-4">
        <div class="card-home-1" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://www1.theladbible.com/images/content/54f056a309fc4.JPG');">
            <h4 class="card-home-title"><%= link_to "FAST", pimped_cars_path %></h4>
          </div>
          </div>
      <div class="col-xs-4">
        <div class="card-home-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://i.ytimg.com/vi/zOWcBe4Maxk/maxresdefault.jpg');">
            <h4 class="card-home-title"><%= link_to "SUPER FAST", pimped_cars_path %></h4>
          </div>
        </div>
      <div class="col-xs-4">
        <div class="card-home-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://www.skitzone.com/wp-content/uploads/2011/01/pimped-car.jpg');">
            <h4 class="card-home-title"><%= link_to "FUR-IOUS", pimped_cars_path %></h4>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/pimped_cars/_map_box.html.erb
<div class="size">
  <div class="map-box" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path pimped_car.photo.path, crop: :fill %>');">
    <div class="map-box-description">
      <h4><%= pimped_car.name %></h4>
      <h4><%= pimped_car.price_per_day %> $</h4>
    </div>
    <%= link_to "", pimped_car_path(pimped_car), class: "map-box-link" %>
  </div>
</div>

app/views/pimped_cars/index.html.erb
<div class="container">
  <div class="content">
    <div class="container-cards">
      <div class="row">
        <%= render 'search_box' %>
        <% @pimped_cars.each do |pimped_car| %>
          <div class="col-xs-12 col-sm-6">
            <%= link_to pimped_car_path(pimped_car), class: "card-link" do %>
              <div class="card-container">
               <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path pimped_car.photo.path, crop: :fill %>');">
                  <div class="card-price">
                    <h4><%= pimped_car.price_per_day%>$</h4>
                  </div>
                </div>
              <!--  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay"> -->
                <div class="card-footer">
                  <div class="card-details">
                    <div class="card-info">
                      <div class="card-name">
                        <h4><%= pimped_car.name %></h4>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="container-map">
      <div id="map"></div>
    </div>
  </div>
</div>



<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var styles = [
    {
        "featureType": "all",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative",
        "elementType": "geometry",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative.country",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative.province",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative.locality",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative.neighborhood",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative.land_parcel",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "all",
        "stylers": [
            {
                "color": "#f2f2f2"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#ffffff"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.natural",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.natural.landcover",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.natural.terrain",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.business",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.government",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.medical",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.park",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.place_of_worship",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.school",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.sports_complex",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
            {
                "saturation": -100
            },
            {
                "lightness": 45
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#252525"
            },
            {
                "weight": "1.00"
            },
            {
                "lightness": "24"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            },
            {
                "weight": "0.85"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.highway.controlled_access",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit.line",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "lightness": "-47"
            }
        ]
    },
    {
        "featureType": "transit.line",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit.station",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit.station.airport",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit.station.bus",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit.station.rail",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#922a2a"
            }
        ]
    },
    {
        "featureType": "transit.station.rail",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "weight": "1.17"
            }
        ]
    },
    {
        "featureType": "transit.station.rail",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#e2e1e1"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    }
];

      var handler = Gmaps.build('Google');
      handler.buildMap({
        provider: {
          styles: styles
        },
        internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>

  <%= javascript_tag do %>
    $( ".card-container" ).hover(
      function() {
        $(this).find('.card-footer').addClass('card-footer-shown');
      }, function() {
        $(this).find('.card-footer').removeClass('card-footer-shown');
      }
    );

  <% end %>
<% end %>

app/views/pimped_cars/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
    <h4 class="text-center"> Riders are waiting for your pimped car, list it! </h4>
     <%= render 'form' %>
    </div>
  </div>
</div>